### ISSUE TITLE
请问数据集可以提供一下国内网盘的吗，Google太大了下不下来

### ISSUE THREAD

**Issue by xlsufo** [xiaobaishu0097/ICLR_VTNet#4]

**Comment by xiaobaishu0097** [comment]
我可以试一下往国内的网盘传一下，不过不能确定能不能行。

Best wishes,
Heming Du

From: Lisong Xu ***@***.***>
Date: Tuesday, 28 March 2023 at 17:48
To: xiaobaishu0097/ICLR_VTNet ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [xiaobaishu0097/ICLR_VTNet] 请问数据集可以提供一下国内网盘的吗，Google太大了下不下来 (Issue #4)

―

**Comment by xlsufo** [comment]
好的，感谢

**Comment by keeper1314** [comment]
请问有国内网盘吗

**Comment by Suhao07** [comment]
请问你下载到数据集了吗？@xlsufo

**Comment by xlsufo** [comment]
> 请问你下载到数据集了吗？[@xlsufo](https://github.com/xlsufo)

没有
